displayName: Copy Header Middleware
type: middleware
import: github.com/12rcu/copyheaders

summary: 'Copies the value of one header to another header'

testData:
  headers:
    - from: from
      to: to
